### ISSUE TITLE
Can I suggest adding a short section to your readme?

### ISSUE THREAD

**Issue by mco-gh** [TechForPalestine/verifiedPetition#10]
I think it would be good to say something to the effect of who you are, not specifically identifying yourself per se, but something like "we are a group of concerned professionals" or "I am a solo developer trying to help the tech industry divest from supporting Israel", etc. The reason I think this is important is I advocated signing this petition to a group of coworkers and I noticed very little github history on this account (and no avatar) so I wanted to be sure this is a legitimate organization, not harvesting email addresses or anything like that.

**Comment by ProfessionalsAgainstGenocide** [comment]
That’s a very good point.
For context, the we went this route is to try and avoid retaliation at our workplaces.

I’ll add a blurb to the petition site :)

For some immediate context though, the effort started with a solo developer, then connected with Tech For Palestine.

Do you have any suggestions on how to best ease people’s concerns without actually revealing anyone’s identity? Would a tweet from T4P or a similar movement help? (And maybe link/embed that tweet/post in the petition site?)

**Comment by mco-gh** [comment]
I found out about you via [this tweet](https://twitter.com/techworkersco/status/1768345106502029537) from the Tech Workers Coalition site, containing a nice graphic, which gave me some confidence this is a sincere effort. If you're affiliated with them, you could mention Tech Workers Coalition and perhaps link to their twitter account or website.

I also think it would help to link to techforpalestine.org, if they're open to using them as a reference. Ideally they would include you in their project list as well, for bidirectional validity.

I totally understand the desire to avoid retribution but it's also important to identify yourself or your group in some way that gives people confidence in your legitimacy. Finding that balance is challenging but some sort of authorship statement would go a long way.

**Comment by mco-gh** [comment]
p.s. I do think a tweet from T4P would be helpful. I would also include that nice poster image from the tweet I referenced in your project readme. Thanks for being so responsive!

**Comment by pbiggar** [comment]
I've been asked about this, so I'll just drop a note about the T4P involvement. This is what in T4P we call a "Community Experiment", which is just people in the discord coming together to build projects. We don't verify their credentials, and we're not involved in the running of the site or the DB.

It seems it would be useful for us (T4P) to learn more on this as folks to verify that their PII isn't being misused. @ProfessionalsAgainstGenocide could you connect with me on the discord or by email so we can do some vetting?

**Comment by ProfessionalsAgainstGenocide** [comment]
Happily! I just DMed you and @‘d you on the discord. Looking forward to setting up some time. I’d love for this project to end up on https://github.com/TechForPalestine :)

**Comment by mco-gh** [comment]
I have a few ideas for the site. I'll follow up the usual github way via issues and PRs.

**Comment by ProfessionalsAgainstGenocide** [comment]
> I have a few ideas for the site. I'll follow up the usual github way via issues and PRs.

Great! I’m excited and looking forward to it🎉

**Comment by pbiggar** [comment]
> I've been asked about this, so I'll just drop a note about the T4P involvement. This is what in T4P we call a "Community Experiment", which is just people in the discord coming together to build projects. We don't verify their credentials or know who they are (beyond their discord names), and we're not involved in the running of the site or the DB.
> 
> It seems it would be useful for us (T4P) to learn more on this as folks want to verify that their PII isn't being misused. @ProfessionalsAgainstGenocide could you connect with me on the discord or by email so we can do some vetting?

This is sorted. We've verified the dev and moved the repo over to t4p org on github.

**Comment by ProfessionalsAgainstGenocide** [comment]
@mco-gh should I keep this issue open to close with PR you’re working on? or are we good to close?

**Comment by mco-gh** [comment]
Leave it open please but you can assign it to me and I'll submit a PR to
address it shortly.
