### ISSUE TITLE
The stats graph has a readability problem

### ISSUE THREAD

**Issue by mco-gh** [TechForPalestine/verifiedPetition#9]
The bars and labels don't line up so it's hard to tell which bar applies to which company.
<img width="468" alt="Screenshot 2024-03-20 at 14 28 11" src="https://github.com/ProfessionalsAgainstGenocide/verifiedPetition/assets/658327/fa66d879-7d44-433b-a7d3-95e57d5511d9">

**Comment by ProfessionalsAgainstGenocide** [comment]
Thank you for pointing that out. We’ll make sure to fix that within the next day or two

**Comment by ProfessionalsAgainstGenocide** [comment]
<img width="1706" alt="image" src="https://github.com/TechForPalestine/verifiedPetition/assets/161672773/9f8e9caa-6eb8-4a9e-864e-e5e3e3bc1018">
new stats just dropped in 199f158 !

**Comment by mco-gh** [comment]
Nice work and thanks!
